kind: pipeline
name: build

steps:
- name: my-build
  image: golang:latest
  commands:
#  - go get github.com/mfridman/tparse #| tparse -all
  - go test  -mod=vendor -v ./src/server/pfs/server -timeout 3600s -json 

services:
- name: etcd
  image: quay.io/coreos/etcd:v3.3.5
  commands:
  - etcd --listen-client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://0.0.0.0:2379
  ports:
  - 2379
