kind: pipeline
name: build

steps:
- name: my-build
  image: golang:latest
  commands:
  - "go test  -mod=vendor -v ./src/server/pfs/server -timeout 3600s | grep -v "$(date +^%FT)"

services:
- name: etcd
  image: quay.io/coreos/etcd:v3.3.5
  ports:
  - 2379
