image: golang:1.9

services:
- name: bitnami/etcd
  command: ["etcd", "--listen-client-urls=http://0.0.0.0:2379", "--advertise-client-urls=http://0.0.0.0:2379"]

unit_tests:
  script: go test -v ./src/server/pfs/server -timeout 60 | grep -v "$(date +^%FT)"
