image: golang:1.13

services:
- name: bitnami/etcd
  command: ["etcd", "--listen-client-urls=http://0.0.0.0:2379", "--advertise-client-urls=http://0.0.0.0:2379"]

variables:
  ALLOW_NONE_AUTHENTICATION: "yes"

unit_tests:
  script: go test -mod=vendor -v -timeout 60s ./src/server/pfs/server  | grep -v "$(date +^%FT)"
